# Generated by Django 4.1.1 on 2022-09-13 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='bookings',
            fields=[
                ('lane_nr', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
    ]
