# Generated by Django 4.1.1 on 2022-09-17 15:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='booking_time_slots',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
            ],
        ),
        migrations.RenameField(
            model_name='bookings',
            old_name='end_date',
            new_name='date',
        ),
        migrations.RemoveField(
            model_name='bookings',
            name='start_time',
        ),
        migrations.AddField(
            model_name='bookings',
            name='time_slot',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='bookings.booking_time_slots'),
            preserve_default=False,
        ),
    ]
