# Generated by Django 4.1.1 on 2022-09-17 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_booking_time_slots_rename_end_date_bookings_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookings',
            name='time_slot',
            field=models.CharField(default='No time slot', max_length=13),
        ),
    ]
