# Generated by Django 4.1.1 on 2022-09-17 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_alter_bookings_booker_phone_alter_bookings_time_slot'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookings',
            name='lane_nr',
        ),
        migrations.AddField(
            model_name='bookings',
            name='lanes',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='bookings',
            name='player_amount',
            field=models.IntegerField(default=1),
        ),
    ]
