# Generated by Django 4.1.1 on 2022-09-17 22:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0006_alter_bookings_booker_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookings',
            name='lanes',
        ),
        migrations.CreateModel(
            name='booked_lanes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookings.bookings')),
                ('lane_nr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookings.lanes')),
                ('time_slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookings.booking_time_slots')),
            ],
            options={
                'unique_together': {('booking', 'lane_nr', 'time_slot', 'date')},
            },
        ),
    ]
