# Generated by Django 4.1.1 on 2022-09-17 22:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0007_remove_bookings_lanes_booked_lanes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookings',
            name='time_slot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookings.booking_time_slots'),
        ),
    ]
